### ISSUE TITLE
Return Electrode - x location

### ISSUE THREAD

**Issue by gnieuwenhuis** [simpeg-research/casingSimulations#3]
Simple problem with how the x location of the return electrode is found - the code looks for cells between 90 and 110% of the x location, but this is mesh dependent. 

I used a simple but inelegant fix, I'm sure there's other ways:
```python
xtmp=np.cumsum(mesh.hx)
hxtmp=mesh.hx[np.where(np.absolute(xtmp-src_b[0])==np.absolute(xtmp-src_b[0]).min()]
surface_electrodex=(
    (mesh.gridFz[:,0] > src_b[0] - (0.5*hxtmp)) &
    (mesh.gridFz[:,0] < src_b[0] + hxtmp))
)
```

**Comment by lheagy** [comment]
Thanks @gnieuwenhuis! I recently noticed this as well, what I am thinking to do is actually specify a `src_b_closest` on the source that just uses the `closestPoints` util in discretize. I have a first-pass locally. I will put it on a pr shortly!

**Comment by lheagy** [comment]
Actually, I have pushed this change, see what you think: https://github.com/lheagy/casingResearch/blob/master/casingSimulations/sources.py#L52 

(P.S. if you are starting to use this repo a bit - I will try to follow better development practices in terms of using pull requests instead of just pushing to master :) )

**Comment by gnieuwenhuis** [comment]
Looks good - also having the separate class allowing line sources without coupling to the casing is also handy for playing around with the models.

(I wouldn't worry too much about better development practice here - I'm using the files as a sandbox and basically have my own (very messy) local branch which I'm playing around with to get certain models run ... not very conducive to good development practice anyways!)
