### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by gnieuwenhuis** [simpeg-research/casingSimulations#5]
Just some ideas for allowing more realistic casing models:

- allow the definition of a more realistic background conductivity (e.g. allow sigma_back to take in a 'CC' model file)

- Allow conductivity of the casing to change with depth (conductance can then be used to account for multiple casing strings)

- even better than above (but complicates a number of functions) - allow multiple (overlapping) casing strings with different radii and parameters

No push, just wanted to pass along ideas that apply to what I'm doing

**Comment by lheagy** [comment]
Thanks @gnieuwenhuis!

- Agreed, being more flexible with the conductivity model would be helpful. I guess we maybe want both layered descriptions (full 3D models get a bit tricky with the cyl mesh - not out of the question, but need to get some interpolation in place. Layer likely accomplish a lot of what is needed at the moment) 

- how long is a typical segment? 3m? 

I am thinking that maybe we want to split up the `casingParameters` object into multiple objects that we can hook up - one of the background, and one of the casing model. Then the construction of a physical property model would take both: construct the background then put the casing on top.

**Comment by gnieuwenhuis** [comment]
- I think you're right - a layered model would cover what is needed

- By casing segments I mean multiple casing types in a single well. For example, nearly all O&G wells have a shallow surface casing with a large diameter, and at least one smaller diameter segment which overlaps the surface casing, but continues deeper to the bottom of the well. The surface casing is typically a few hundred meters in length. There are also casing sections (joints), each about 12m long, but I would be very surprised if the change in casing parameters associated with the threading between joints affects the current flow enough to be measurable.

Splitting up the `casingParameters` object makes sense to me. Building the background model (and having the potential to do interpolation) could become a useful object in and of itself.

**Comment by lheagy** [comment]
I have an initial implementation of this through the `model` module. There is now
```
from casingSimulations import model
model.Wholespace
model.Halfspace
model.SingleLayer
``` 
and similarly models that include casing
```
model.CasingInWholespace
model.CasingInHalfspace
model.CasingInSingleLayer
```
The latter inherit the background and a casing parameter mixin class. So basically, once we have created any type of background model class, it is fairly straight-forward to then extend to also include a casing in that background (eg. see https://github.com/lheagy/casingSimulations/blob/master/casingSimulations/model.py#L348)

**Comment by gnieuwenhuis** [comment]
Looks like a nice flexible implementation - I've begun implementation into my workflow and I'll let you know if I have any issues. 

Should I close this issue?

**Comment by lheagy** [comment]
sure, sounds good! and feel free to re-open if you run into any issues
